package com.fusibang.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-22T21:04:40.096+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SmSWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SmSWebServiceSoap {

    @WebMethod(operationName = "QueryOverage", action = "http://tempuri.org/QueryOverage")
    @RequestWrapper(localName = "QueryOverage", targetNamespace = "http://tempuri.org/", className = "com.fusibang.webservice.QueryOverage")
    @ResponseWrapper(localName = "QueryOverageResponse", targetNamespace = "http://tempuri.org/", className = "com.fusibang.webservice.QueryOverageResponse")
    @WebResult(name = "QueryOverageResult", targetNamespace = "http://tempuri.org/")
    public com.fusibang.webservice.WsOverageResponse queryOverage(

            @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
                    String userid,
            @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
                    String account,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password
    );

    @WebMethod(operationName = "SendSms", action = "http://tempuri.org/SendSms")
    @RequestWrapper(localName = "SendSms", targetNamespace = "http://tempuri.org/", className = "com.fusibang.webservice.SendSms")
    @ResponseWrapper(localName = "SendSmsResponse", targetNamespace = "http://tempuri.org/", className = "com.fusibang.webservice.SendSmsResponse")
    @WebResult(name = "SendSmsResult", targetNamespace = "http://tempuri.org/")
    public WsSendResponse sendSms(

            @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
                    String userid,
            @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
                    String account,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
                    String mobile,
            @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
                    String content,
            @WebParam(name = "sendTime", targetNamespace = "http://tempuri.org/")
                    String sendTime,
            @WebParam(name = "extno", targetNamespace = "http://tempuri.org/")
                    String extno
    );

    @WebMethod(operationName = "QueryCall", action = "http://tempuri.org/QueryCall")
    @RequestWrapper(localName = "QueryCall", targetNamespace = "http://tempuri.org/", className = "com.fusibang.webservice.QueryCall")
    @ResponseWrapper(localName = "QueryCallResponse", targetNamespace = "http://tempuri.org/", className = "com.fusibang.webservice.QueryCallResponse")
    @WebResult(name = "QueryCallResult", targetNamespace = "http://tempuri.org/")
    public WsCallResponse queryCall(

            @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
                    String userid,
            @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
                    String account,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "callNum", targetNamespace = "http://tempuri.org/")
                    String callNum
    );

    @WebMethod(operationName = "QueryStatus", action = "http://tempuri.org/QueryStatus")
    @RequestWrapper(localName = "QueryStatus", targetNamespace = "http://tempuri.org/", className = "com.fusibang.webservice.QueryStatus")
    @ResponseWrapper(localName = "QueryStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.fusibang.webservice.QueryStatusResponse")
    @WebResult(name = "QueryStatusResult", targetNamespace = "http://tempuri.org/")
    public WsStatusResponse queryStatus(

            @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
                    String userid,
            @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
                    String account,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "statusNum", targetNamespace = "http://tempuri.org/")
                    String statusNum
    );
}
