package com.fusibang.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-22T21:04:40.154+08:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "SmSWebService",
                  wsdlLocation = "http://39.98.237.121:8088/SmsWebService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class SmSWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SmSWebService");
    public final static QName SmSWebServiceSoap12 = new QName("http://tempuri.org/", "SmSWebServiceSoap12");
    public final static QName SmSWebServiceSoap = new QName("http://tempuri.org/", "SmSWebServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://39.98.237.121:8088/SmsWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SmSWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://39.98.237.121:8088/SmsWebService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SmSWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SmSWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmSWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SmSWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SmSWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SmSWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SmSWebServiceSoap
     */
    @WebEndpoint(name = "SmSWebServiceSoap12")
    public SmSWebServiceSoap getSmSWebServiceSoap12() {
        return super.getPort(SmSWebServiceSoap12, SmSWebServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmSWebServiceSoap
     */
    @WebEndpoint(name = "SmSWebServiceSoap12")
    public SmSWebServiceSoap getSmSWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(SmSWebServiceSoap12, SmSWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns SmSWebServiceSoap
     */
    @WebEndpoint(name = "SmSWebServiceSoap")
    public SmSWebServiceSoap getSmSWebServiceSoap() {
        return super.getPort(SmSWebServiceSoap, SmSWebServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmSWebServiceSoap
     */
    @WebEndpoint(name = "SmSWebServiceSoap")
    public SmSWebServiceSoap getSmSWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(SmSWebServiceSoap, SmSWebServiceSoap.class, features);
    }

}
